### ISSUE TITLE
[Bug] Missing terminal symbol when using URScript Interface

### ISSUE THREAD

**Issue by SteveGrehl** [Zagitta/ur_modern_driver#18]
Hallo,

I think I found a bug within the URScript Interface. It is designed to simply, pass std_msg.String messages to the UR robot. When using the current (a2137b4762a69b056da4ec06233b199daaef4439) version this is done, but the UR robot wont execute any commands.

This behavior can be tested by:
* starting the driver ` roslaunch ur_modern_driver ur5_bringup_joint_limited.launch robot_ip:=<myip>` 
* sending a simple std_msg.String: ` set_digital_out(2,True)` to `/ur_driver/URScript`  using, eg _rqt_
* checking the I/O Tab, if Digital Output 2 is blue - it isn't in my case

After testing with a [script](http://www.zacobria.com/universal-robots-zacobria-forum-hints-tips-how-to/script-via-socket-connection/) the communication, I found out that the terminal symbol `'\n'` was missing.

I propose the following [patch](https://cloud.tu-freiberg.de/index.php/s/ZYra76wU8H9PLwT)(pw:ur_modern_driver):
```
From 40f826bbfd4548d2edc62517c7eec225b4e43c68 Mon Sep 17 00:00:00 2001
From: Steve Grehl <Steve.Grehl@informatik.tu-freiberg.de>
Date: Sat, 24 Feb 2018 15:07:51 +0100
Subject: [PATCH] [Bugfix] Added terminal symbol '\n' to URScript program

---
 src/ur/commander.cpp | 6 ++++--
 1 file changed, 4 insertions(+), 2 deletions(-)

diff --git a/src/ur/commander.cpp b/src/ur/commander.cpp
index 9b85865..55a34b1 100644
--- a/src/ur/commander.cpp
+++ b/src/ur/commander.cpp
@@ -3,8 +3,10 @@
 
 bool URCommander::write(const std::string &s)
 {
-  size_t len = s.size();
-  const uint8_t *data = reinterpret_cast<const uint8_t *>(s.c_str());
+  std::string msg(s);
+  msg = s + '\n';
+  size_t len = msg.size();
+  const uint8_t *data = reinterpret_cast<const uint8_t *>(msg.c_str());
   size_t written;
   return stream_.write(data, len, written);
 }
--
libgit2 0.26.0
```

I tested it with:
* Version 3.3.0.145 (Simulation)
* Version 3.5.2.10778 (Simulation, Real robot)

The bug was present in firmwares in the versions (3.2.18654, 3.2.21545, 3.3.0.145, 3.4.0.39, 3.5.1.10661, 3.5.2.10778)

**Comment by Zagitta** [comment]
Should be fixed in 7eaa518.
Thank you for the report and patch suggestion 🎉
