### ISSUE TITLE
Start up of robot not possible

### ISSUE THREAD

**Issue by mat-l** [Zagitta/ur_modern_driver#19]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Current Behavior

roscore should start and the UR10 should be brought up

## Your Environment

* Version used: kinetic
* ROS version: 1.12.12
* Operating System and version: Ubuntu 16.04
* I cloned all necessary packages such as industrial_core, ros_control, universal_robot and catkin_make is executing without errors

## Log file
I perform the command:
```
roslaunch ur_modern_driver /home/ws_development/src/universal_robot/ur_modern_driver/launch/ur10_bringup.launch robot_ip:=160.69.69.101
```
or additionally
```
roslaunch ur_modern_driver ur10_bringup.launch robot_ip:=160.69.69.101
```
ROS ist not starting up, instead I get the following error displayed:
```
[/home/ws_development/src/universal_robot/ur_modern_driver/launchur10_bringup.launch] is neither a launch file in package [ur_modern_driver] nor is [ur_modern_driver] a launch file name
The traceback for the exception was written to the log file
```

What could be the problem or solution, to start up the system. Did I do any small mistake after setting up the new PC and installing the different software packages?

Best
matl

**Comment by mat-l** [comment]
@ThomasTimm

**Comment by gavanderhoorn** [comment]
@mat-l wrote:
> ```
> roslaunch ur_modern_driver /home/ws_development/src/universal_robot/ur_modern_driver/launch/ur10_bringup.launch robot_ip:=160.69.69.101
> ```

This is not a well formed `roslaunch` command: either use an absolute or relative file system path to a `.launch` file *or* use the `$pkg $launchfile` syntax. Both won't work.

**Comment by gavanderhoorn** [comment]
@mat-l wrote:
> I cloned all necessary packages such as industrial_core, ros_control, universal_robot

Note that `industrial_core` and `ros_control` (and probably `universal_robot` as well) can just as well by installed using `apt`, no need to have those in your workspace.

**Comment by mat-l** [comment]
Ah great thanks, it is working now. I just forgot the source devel/setup.bash which I confused with this source command "source /opt/ros/kinetic/setup.bash"
