### ISSUE TITLE
Failed to validate trajectory

### ISSUE THREAD

**Issue by atyshka** [Zagitta/ur_modern_driver#23]
I'm running this driver with the ur10_moveit_config and I'm running into an error when attempting to execute plans:
```
[ WARN] [1528212559.376181626]: Failed to validate trajectory: couldn't receive full current joint state within 1s
```

This error seems to occur randomly and the only solution is quitting and restarting the moveit config and the ur driver. The issue happens roughly half the time and makes the driver quite unusable for me.

**Comment by gavanderhoorn** [comment]
That message is a MoveIt warning. It is not printed by `ur_modern_driver`, nor this fork.

Are you using octomap updates to your planning scene by any chance?

**Comment by gavanderhoorn** [comment]
I'm going to close this now, as it doesn't seem like an issue with the driver.

If/when you feel it's not a Moveit issue, please re-open, but also please add information we need to help you, such as:

 - what platform you're running this on (ie: PC or embedded arm)
 - what OS
 - how you installed ROS and this package
 - what software version your UR is running
 - how you are connecting to the robot controller (wired or wireless)

etc.

People forget to tell us these things all the time, and it makes diagnosing issues quite impossible for us.
