### ISSUE TITLE
Problems with running on UR5

### ISSUE THREAD

**Issue by Brudasoe** [Zagitta/ur_modern_driver#24]
Hi, I am trying to utilize this version of ur_modern_driver in my project, and I've come across a problem.
When trying to run the ros_control node with velocity based control and default PID controller parameters the robot gets protective stopped in the middle of the first move. When I decrease P values it goes more slowly, but the movement is interrupted by slow jerks and erros occur:
```
[ WARN] [1529417769.185625993]: Controller /vel_based_pos_traj_controller failed with error code PATH_TOLERANCE_VIOLATED

[ WARN] [1529417769.185846757]: Controller handle /vel_based_pos_traj_controller reports status ABORTED

[ INFO] [1529417769.205158095]: Completed trajectory execution with status ABORTED ... 
                                        
[ INFO] [1529417769.277249613]: ABORTED: Solution found but controller failed during execution   
                                 
[ERROR] [1529417769.277592]: Reaching TARGET position failed. Check robot connection.  
```
and sometimes
```
[ERROR] [1529417729.877805883]:                                                                                                        
Invalid Trajectory: start point deviates from current robot state more than 0.01                                                       
joint 'shoulder_pan_joint': expected: -0.999794, current: -0.974795   
```
The robot then reaches final position of the first move but runs even more slowly towards the next one.
I guess this may be similar to the other issues related with vibrations here in the modern_ur_drive repositiories, but looking at them I can't figure out what could else be done to fix this..
I'm using Ubuntu 16, ROS Kinetic and UR 3.5.2.10778
While using the default packages the program ran through all the moves without problem, but I've had problems with jerky motions  and thats why I wanted to test this package. 
If there is need for any additional info please ask.

**Comment by gavanderhoorn** [comment]
Just making sure: you're not using any wireless links between you and the robot?

**Comment by Brudasoe** [comment]
No, the communication is done via gigabit network card and switch. I have additional two cameras connected to this switch but they operate at 1Hz. Do you suggest it's better to change the UR software version for now?

**Comment by gavanderhoorn** [comment]
I'm not necessarily suggesting anything, just doing some expectation management.

**Comment by Brudasoe** [comment]
Ok, so main problem was with the PID values, I found them to be a lot different than the default values:
```
shoulder_pan_joint: {p: 18.0,  i: 270.0, d: 0.0001, i_clamp: 20.14}
shoulder_lift_joint: {p: 18.0,  i: 270.0, d: 0.0001, i_clamp: 20.14}
elbow_joint: {p: 18.0,  i: 270.0, d: 0.0001, i_clamp: 20.14}
wrist_1_joint: {p: 18.0,  i: 270.0, d: 0.0001, i_clamp: 20.14}
wrist_2_joint: {p: 18.0,  i: 270.0, d: 0.0001, i_clamp: 20.14}
wrist_3_joint: {p: 18.0,  i: 270.0, d: 0.0001, i_clamp: 20.14}
```
I also found that the reason for the normal jerky movements is due to switch getting overburdened (velocity control got rid of part of the problem, but while adding one more device to the switch it returned to as it was before)

**Comment by gavanderhoorn** [comment]
Thanks for the update.

> I also found that the reason for the normal jerky movements is due to switch getting overburdened (velocity control got rid of part of the problem, but while adding one more device to the switch it returned to as it was before)

Control is sensitive to delay and jitter. The more devices on an ethernet network, the higher the chance of collisions.

**Comment by Brudasoe** [comment]
I had some time to experiment, and it seems that the problem is with network bottleneck at my computer, as you said. It seems that #9 fixed those issues for now (hope it gets accepted eventually).

**Comment by gavanderhoorn** [comment]
Closing as OP reports that this appears to be a local issue.
