### ISSUE TITLE
ee_link changes parent frame when connected to real robot

### ISSUE THREAD

**Issue by felixvd** [Zagitta/ur_modern_driver#26]
## Expected Behavior
The ee_link should be child link to wrist_3_link. It should be the same in simulation and when using the real robot.

## Current Behavior
When I connect to the physical robot, the ee_link frame has a different orientation than during simulation, and is child to the base frame of the robot instead of wrist_3_link. The error might be on my end, but I don't know how I could have changed this detail. 

The screenshots below show the state I expected, during demo.launch of the moveit_config package:
![gripper_demo_1](https://user-images.githubusercontent.com/4535737/43999749-7d9b4bf2-9e4d-11e8-81ca-cecd55b96a87.png)

And the state I get when I connect to the physical robot, with the frames that were connected to ee_link rotated and out of place:
![gripper_real_1](https://user-images.githubusercontent.com/4535737/43999758-ab44ddac-9e4d-11e8-92b7-3f517c9d1cd3.png)
![gripper_tree_1](https://user-images.githubusercontent.com/4535737/43999759-ab691352-9e4d-11e8-9930-c7eb32e6c82b.png)
The tree shows that ee_link is not a child of wrist_3_link anymore, but is connected to the base. It also updates properly when I perform a motion (although the orientation is wrong), which makes me suspect that it's published by the robot driver somewhere.

(I added the prefix because I have multiple robots in the scene, but it should not affect this issue).

## Possible Solution
Did something change in how the firmware reports the position of the EE link? I attached a bag file that I recorded while I was starting up the robot and gripper, and then planned and executed a short motion. Maybe you can use it to see where the wrong transform is coming from.

The bag: 
[2018-08-12-07-29-20.bag.zip](https://github.com/Zagitta/ur_modern_driver/files/2280800/2018-08-12-07-29-20.bag.zip)

## Steps to Reproduce (for bugs)
It should be enough to launch demo.launch of a moveit_config with a UR in it, and then compare it to the scene when connected to a real robot.

## Context
I am using a frame on the end effector to plan motions to pick up stuff. To fix this issue temporarily, I just added a ee_duplicate_link to attach the end effector, so everything works fine for me, but it is still odd behavior and I'd like to figure out what's wrong.

## Your Environment
* Ubuntu 16.04
* Version used: master?
* ROS version: Kinetic
* UR CB version: 3.5.0.10584 (Nov 16 2017)
* Connection setup: wired

**Comment by gavanderhoorn** [comment]
> which makes me suspect that it's published by the robot driver somewhere.

`ee_link` is part of the static kinematic chain defined in the xacros in `ros-industrial/universal_robot/ur_description`. It cannot be changed by something a driver broadcasts, unless you have a 'rogue' TF broadcaster that is changing the transform. In that cause however I would expect you to see a whole lot of other problems.

Further: there are no TF frames published by the driver apart from `tool0_controller`.

Could you please check whether you've made any inadvertent changes to the files in `ur_description`?

**Comment by gavanderhoorn** [comment]
As an aside: the `ee_link` frame might not be what you'd want to use, as it's not a frame that corresponds to anything the robot controller internally defines. `tool0` is aligned with the tool frame of the controller (`tool0_controller` is the same frame, but its pose is broadcast by the controller directly, where `tool0`'s pose is derived from joint states using FK). The chain from `base->tool0` corresponds to the kinematic chain as defined by the controller and the transform should also correspond to the tool frame pose the controller reports (+- effects introduced by calibration).

`ee_link` was left in for bw-compatibility reasons in the xacros in `ur_description` and will be removed in the future. An additional frame will be introduced (`flange`) that will serve as an EEF connection point in the kinematic chain. `tool0` will be a child of that, and additional tool frames should be made siblings of `tool0`.

The `ur_description` xacros don't have that frame yet, but `tool0` is available, and `flange` will be in the exact same location for those robots. It will just not be rotated to have `z+` forward.

See [Working with ROS-Industrial Robot Support Packages](http://wiki.ros.org/Industrial/Tutorials/WorkingWithRosIndustrialRobotSupportPackages) for a short discussion of these frames, and [Coordinate Frames for Serial Industrial Manipulators](http://gavanderhoorn.github.io/rep/rep-xxxx.html) for a candidate REP that is in the making.

**Comment by felixvd** [comment]
Your second edit was right, I was mistaken about the tool/EE frames and defined the `base_frame` and `tool_frame` args in the launch file:

```
  <node name="b_bot_ur_driver" pkg="ur_modern_driver" type="ur_driver" output="screen" ns="b_bot_controller">
    <param name="prefix" type="str" value="b_bot_" />
    <param name="robot_ip_address" type="str" value="$(arg robot_ip_b)" />
    <param name="reverse_port" type="int" value="50002" /> 
    <param name="min_payload" type="double" value="$(arg min_payload)" />
    <param name="max_payload" type="double" value="$(arg max_payload)" />
    <param name="max_velocity" type="double" value="$(arg max_velocity)" />
    <param name="servoj_time" type="double" value="$(arg servoj_time)" />
    <param name="base_frame" type="str" value="b_bot_base" />
    <param name="tool_frame" type="str" value="b_bot_ee_link" />
    <param name="require_activation" type="str" value="$(arg require_activation)" />
    <param name="shutdown_on_disconnect" type="bool" value="$(arg shutdown_on_disconnect)"/>
    <remap from="joint_states" to="/joint_states"/>
  </node>
```

Removing the two fixes this issue. I completely forgot that I set these. Afterwards, I found that the following setting in my URDF seems to lead to this wonky behavior:

```
  <joint name="world_b_bot_joint" type="fixed">
    <parent link="world" />
    <child link = "b_bot_base_link" />
    <origin xyz="${b_bot_x} ${b_bot_y} ${bots_z}" rpy="0.0 0.0 ${-pi}" />
  </joint>
```

![gripper_fixed_1](https://user-images.githubusercontent.com/4535737/44001243-6b054bb6-9e69-11e8-8089-8a0b58a37b89.png)

Thanks for the heads up and the links to the documentation too. Cheers

**Comment by gavanderhoorn** [comment]
@felixvd wrote:
> Afterwards, I found this wonky behavior but I hope it's just my modifications in the URDF

actually, I believe if you *remove* those two params, the default of the driver (or this fork) is to use `base_link->tool0_controller` ([here](https://github.com/Zagitta/ur_modern_driver/blob/a2f5f4bed593057fa686d6c903fb41f14509917f/src/ros_main.cpp#L96
)). `base_link` is 180 degrees rotated wrt `base` (this is historical, will be rectified).

I would recommend to `include` the `ur_common.launch` file *or* leave the two params in and just use the default values: `base` and `tool0_controller`.
