### ISSUE TITLE
Launch Files "use_ros_control" not passable through bringup

### ISSUE THREAD

**Issue by SpencerFishman** [Zagitta/ur_modern_driver#34]
## Issue/Feature Request
In order to use ros_control, ur_common.launch must be executed with the argument `use_ros_control = true`. In the current system, the solution would be to simply call ur5_ros_control.launch. However, what if I want to start the robot with a different controller loaded in? other than the velocity_based_pos_trajectory_controller. The argument `use_ros_control` should be expected by the bringup launch files and then passed to ur_common.

## Ideal Behavior
This way, the user can just include `ur5_bringup` in their launch file with `use_ros_control = true` and handle the controllers themselves.

**Comment by gavanderhoorn** [comment]
This fork is no longer maintained. You'll want to post this on the main issue tracker at `ros-industrial/ur_modern_driver`.
